import Navbar from '@/components/Navbar'
import { cn } from '@/lib/utils'
import '@/styles/globals.css'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { Toaster } from "@/components/ui/toaster"
import Providers from '@/components/Providers'


const inter = localFont({
  src: [
    {
      path: '../public/fonts/Inter-Regular.ttf',
      weight: '400'
    },
  ],
  variable: '--font-inter'
})

export const metadata: Metadata = {
  title: 'seddit social media pp',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
 

}: {
  children: React.ReactNode,
  authModal:React.ReactNode,}) {
  return (
    <html lang="en" className={cn("bg-white text-slate-900 antialiased light",inter.className)}>
      <body className='min-h-screen pt-12 bg-slate-50 antialiased'>
        <Providers>
        <Navbar/>

        <div className='container max-w-7xl mx-auto h-full pt-12 '>

        {children}
        </div>
        <Toaster></Toaster>
        </Providers>
        </body>
    </html>
  )
}
